### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by simcha-c** [sewilee/AirDnD#3]
- [x] Make sure to add timestamps for _all_ your tables.

`listings table`
- [x] you will also need a `longitude` and `latitude` column to show it on a map, so please add those columns.
- [x] What is `type`?
- [x] maybe try to add some amenities to your listings? Does it have wifi, things like that.
- [x] Also, some more info about the listing would be great. For example, how many rooms does this listing have? etc.

- [x] We need a `reviews` table.

Everything else looks great! Great job!

**Comment by sewilee** [comment]
Other than the mentioned issues above, I made some changes to the table: 
- added an amenities table 
- added listing features tables ( joint table of amenities and listing)
